export const palette = {
  light: {
    background: "#FFFFFF",
    backgroundElement: "#F4F1EF",
    backgroundSelected: "#ECE6E2",
    surface: "#FFFFFF",
    surfaceMuted: "#F8E9E1",
    text: "#201815",
    textSecondary: "#6F625D",
    border: "#E3C4B7",
    accent: "#B02E00",
    accentSoft: "#FFD8C8",
    secondary: "#177FD8",
    success: "#2E8B57",
    danger: "#C43D2B",
    calendarMenstruationLight: "#F08080",
    calendarMenstruationModerate: "#D00000",
    calendarMenstruationHeavy: "#9D0208",
    calendarOvulation: "#039BE5",
    calendarPill: "#32CD32",
    calendarOff: "transparent",
    symptomsSymptoms: "#FFA07A",
    symptomsDischarge: "#87CEFA",
    symptomsLibido: "#FFB6C1",
    symptomsExercise: "#20B2AA",
    symptomsMoods: "#DA70D6",
  },
  dark: {
    background: "#000000",
    backgroundElement: "#121212",
    backgroundSelected: "#1D1D1D",
    surface: "#161616",
    surfaceMuted: "#221A19",
    text: "#FFF6F3",
    textSecondary: "#D0B8AF",
    border: "#5D433D",
    accent: "#FFB499",
    accentSoft: "#5B2411",
    secondary: "#8CC8FF",
    success: "#7FD3A2",
    danger: "#FF9A8C",
    calendarMenstruationLight: "#F08080",
    calendarMenstruationModerate: "#D00000",
    calendarMenstruationHeavy: "#9D0208",
    calendarOvulation: "#4FC3F7",
    calendarPill: "#32CD32",
    calendarOff: "transparent",
    symptomsSymptoms: "#FFA07A",
    symptomsDischarge: "#87CEFA",
    symptomsLibido: "#FFB6C1",
    symptomsExercise: "#20B2AA",
    symptomsMoods: "#DA70D6",
  },
} as const;

export type ThemeName = keyof typeof palette;
export type ThemeColors = (typeof palette)[ThemeName];
